### ISSUE TITLE
Draw cards before placing Ocean/Colony

### ISSUE THREAD

**Issue by duckmammal** [bafolts/terraforming-mars#1692]
I always want to know which cards I have and which cards are not in the game *before* I place my greenery. I should be able to do this according to the rules, and I see no reason why anyone would want to place a greenery before getting more information.

**Comment by kevinb9n** [comment]
As a general statement I think we would want all information-gaining effects (pretty much just card draws) to happen before any effects requiring user choices, except that:

* It must know the action will definitely be able to complete (e.g. Reds policy)
* It must not apply to Sponsored Academies, "discard THEN"
* or to Mars University, "discard TO".

**Comment by kevinb9n** [comment]
This looks like the full list to me

* Convoy From Europa
* Large Convoy (two choices!)
* Research Colony

**Comment by kevinb9n** [comment]
The first two can fail only under Reds I believe, which I guess is easily checked for. The third just needs to know that any colony is still available. If getting the cards first means the player can't cancel once they see they don't like any of the colony choices after all, then so be it, I'd say.

**Comment by nwai90** [comment]
Fixed by @Lynesth

**Comment by Lynesth** [comment]
Note: I didn't fix anything, just checked that all applicable cards behave properly.

**Comment by duckmammal** [comment]
I wanted to actually comment about this again. 

When Spin-Off Department is in play, you should draw the cards before deciding anything about whatever card you're doing an action for.
Likewise, Large Convoy should draw cards first, ask you to place an ocean second (in case that draws you into more cards) and then finally ask whether you want plants or animals.
A similar situation is true with Imported Hydrogen.

**Comment by Lynesth** [comment]
@duckmammal Regarding Imported Hydrogen, why does it matter to have new cards in hand before picking plants or animals ?

**Comment by Lynesth** [comment]
Also regarding Spin-Off Department, I believe it properly triggers the draw before asking you anything about the card you played.

**Comment by duckmammal** [comment]
Let's say it's the last round of the game, and that I desperately want to build a greenery, but I don't have enough plants to do it. If placing an ocean could ever conceivably draw me into a card that could give me more plants, then that might push me to choose gaining 3 plants over another option.

This is just one scenario, but in reality it almost never makes sense to do the thing that gives you more options last, if all else is equal.

**Comment by kevinb9n** [comment]
Just to throw a wrench into the works :-), if #1846 were to ever happen, then it may become annoying that cards are automatically drawn eagerly.

A satisfying but sadly complex solution would be to display only card backs in hand from the time they are drawn until whenever the commitment to draw them is irrevocably committed to the database. The player could then click to reveal them, but would know that by doing so they are ceding their right to ever cancel or undo the action.
