### ISSUE TITLE
Timers in drafting

### ISSUE THREAD

**Issue by sienmich** [bafolts/terraforming-mars#2159]
When somebody is drafting he does not know if others are still drafting or are waiting.

I would like their timers to stop (instead of jumping later back in time).
Additionally I'm thinking about simple log messages, for example:

```
Drafting - Round 1 - Red, Blue, Green
Drafting - Round 2 - Blue, 
```

I'm thinking about resolving it by using the `waitForUpdate` method from `WaitingFor.ts`. It means that additionaly every 5s during drafting (and card choosing) client would ping server to check what other players are doing.

What do u think? Only timers or also log info?

**Comment by kevinb9n** [comment]
I think it's fair for players to know which other players are ready.

And when thinking/talking about this, I'd like folks to at least know about the #2101 idea too.

**Comment by kberg** [comment]
Pretty sure this is fixed. Reopen if I am wrong?

**Comment by sienmich** [comment]
No, it is still not done. When you are drafting, you don't know the state of other players, as described above.

**Comment by kberg** [comment]
Whoops!
