### ISSUE TITLE
Server crash on Turmoil Undo turn action

### ISSUE THREAD

**Issue by alrusdi** [bafolts/terraforming-mars#695]
I don't sure about the actual reason. But stack trace it always like this:

```
/src/turmoil/Turmoil.js:272
            return GlobalEventDealer_1.getGlobalEventByName(element.name);
                                                                    ^

TypeError: Cannot read property 'name' of null
    at /src/turmoil/Turmoil.js:272:69
    at Array.map (<anonymous>)
    at Turmoil.loadFromJSON (/dist/src/turmoil/Turmoil.js:271:88)
    at Game.loadFromJSON (/dist/src/Game.js:1081:36)
    at Statement.<anonymous> (/dist/src/database/SQLite.js:61:18)
```

**Comment by pierrehilbert** [comment]
Do you have the last version?
Because previously, the getGlobalEventByName wasn't aware of colony and venus global events, I corrected it yesterday.

**Comment by alrusdi** [comment]
I don't sure. Will check it and reopen this issue if bug is still there
